{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-mychart.serviceAccountName" . }}
  labels:
{{ include "external-mychart.labels" . | nindent 4 }}
{{- end -}}
