apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "toolbox.fullname" . }}
  labels:
    {{- include "toolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "toolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "toolbox.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "toolbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: uptime
          hostPath:
            path: /var/lib/lxcfs/proc/uptime
            type: File
      containers:
        - name: {{ .Chart.Name }}
          image: airdb/toolbox
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - "900"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
