apiVersion: v1
data:
  oauth2-proxy.cfg: |
    ## OAuth2 Proxy Config File
    ## https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example

    http_address = ":4180"

    ## The OAuth Client ID, Secret
    client_id = "{{ .Values.service.client_id }}"
    client_secret = "{{ .Values.service.client_secret }}"

    cookie_secret = "{{ .Values.service.cookie_secret }}"
    cookie_domain = "{{ .Values.service.cookie_domain }}"
    # defaults to the "https://" + requested host header + "/oauth2/callback"
    set_xauthrequest = true

    ## Email Domains to allow authentication for (this authorizes any email on this domain)
    ## for more granular authorization use `authenticated_emails_file`
    ## To authorize any email addresses use "*"
    email_domains = [
        "gmail.com",
    ]
    
    auth_tokens = [
    	""
    ]


kind: ConfigMap
metadata:
  name: oauth2-proxy
