{{- $fullName := include "bbhj-ingress.fullname" . -}}
apiVersion: v1
data:
  qcloud_cert_id: "{{ .Values.service.qcloud_cert_id | b64enc }}"
  #qcloud_cert_id: "{{ .Values.ingress.annotations.qcloud_cert_id | b64enc }}"
kind: Secret
metadata:
  labels:
    qcloud-app: {{ $fullName }}
  name: {{ $fullName }}
  namespace: default
type: Opaque
